<a href="https://colab.research.google.com/github/myxsan/fcc-dl/blob/main/pytorch_fundamentals/pytorch_fundamentals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## Pytorch Fundamentls


In [1]:
import torch

print(torch.__version__)

2.8.0+cu126


In [2]:
!nvidia-smi

/bin/bash: line 1: nvidia-smi: command not found


## Introduction to Tensors

### Creating Tensors

PyTorch tensors are created using
```torch.tensor()```


In [3]:
# Scalar
scalar = torch.tensor(7)
scalar

tensor(7)

In [4]:
scalar.ndim

0

In [5]:
# Get tensor back as Python int
scalar.item()

7

In [6]:
# Creating a vector
vector = torch.tensor([7, 7])
vector

tensor([7, 7])

In [7]:
vector.ndim

1

In [8]:
vector.shape

torch.Size([2])

In [9]:
# Creating a Matrix
matrix = torch.tensor([[7,8],
                      [9,10]])

matrix

tensor([[ 7,  8],
        [ 9, 10]])

In [10]:
matrix.ndim

2

In [11]:
matrix.shape

torch.Size([2, 2])

In [12]:
matrix[0]

tensor([7, 8])

In [13]:
TENSOR = torch.tensor([[[1,2,3],
                        [3,6,9],
                        [2,4,5]]])

TENSOR

tensor([[[1, 2, 3],
         [3, 6, 9],
         [2, 4, 5]]])

In [14]:
TENSOR.ndim

3

In [15]:
TENSOR.shape

torch.Size([1, 3, 3])

In [16]:
TENSOR[0]

tensor([[1, 2, 3],
        [3, 6, 9],
        [2, 4, 5]])

### Random Tensors

Random tensors are important because the way many neural networks learn is that they start with tensors full of random numbers and then adjust random numbers to better represent data.

`Start with random numbers -> look at data -> update random numbers -> look at data -> update random numbers`

To create a random tensor use ```torch.rand()```

In [17]:
random_tensor = torch.rand(2,3,4)
random_tensor

tensor([[[0.3980, 0.0427, 0.6424, 0.9820],
         [0.4772, 0.0315, 0.5157, 0.3663],
         [0.8324, 0.2718, 0.6421, 0.5752]],

        [[0.8605, 0.7709, 0.6614, 0.4340],
         [0.3376, 0.4091, 0.3220, 0.9144],
         [0.2834, 0.1450, 0.4838, 0.7569]]])

In [18]:
random_tensor.ndim

3

In [19]:
random_image_size_tensor = torch.rand(size=(224, 224, 3)) # height, width, color channels (R,G,B)
random_image_size_tensor.shape, random_image_size_tensor.ndim

(torch.Size([224, 224, 3]), 3)

### Zero and One Tensors

To create a zeros tensor use ```torch.zeros```
<br>
To create a ones tensor use ```torch.ones```


In [20]:
zeros = torch.zeros(size=(3,4))
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [21]:
zeros * random_tensor

tensor([[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]])

In [22]:
ones = torch.ones(size=(3,4))
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [23]:
ones.dtype

torch.float32

### Creating a range of tensors and tensors-like

To create a range tensor use ```torch.arange```
<br>
To creata a tensors like find a suitable function for your data

In [24]:
torch.arange(start = 10, end = 7000, step = 333)

tensor([  10,  343,  676, 1009, 1342, 1675, 2008, 2341, 2674, 3007, 3340, 3673,
        4006, 4339, 4672, 5005, 5338, 5671, 6004, 6337, 6670])

In [25]:
# Creating a zeros tensors like

random_zero = torch.zeros_like(input=random_tensor)
random_zero

tensor([[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]])

## Tensor Datatypes

by default tensor datatype is float32 for floats and int64 for integers

**Note:** Tensor datatypes is one of the most 3 big issues with PyTorch & deep learing

1. Tensors not right datatype
2. Tensors not right shape
3. Tensors not on the right device

In [26]:
float_32_tensor = torch.tensor([3.0, 6.0, 9])

none_type_tensor = torch.tensor([3.0, 6.0, 9], dtype=None)

float_32_tensor.dtype, none_type_tensor.dtype

(torch.float32, torch.float32)

In [27]:
tensor_properties = torch.tensor([3.0, 6.0, 9],
                                 dtype=None, # Data type of tensor
                                 device=None, # CPU or GPU or TPU
                                 requires_grad=False) # Whether or not to track gradients with this tensors operations.

In [28]:
float_16_tensor = float_32_tensor.type(torch.float16) # torch.half also works

float_16_tensor.dtype

torch.float16

In [29]:
float_16_tensor * float_32_tensor

tensor([ 9., 36., 81.])

In [30]:
int_32_tensor = torch.tensor([3, 6, 9], dtype=torch.int32)

int_32_tensor.dtype

torch.int32

In [31]:
float_32_tensor * int_32_tensor

tensor([ 9., 36., 81.])

### Getting Information from Tensors

1. To get datatype from a tensor, can use `tensor.dtype`
2. To get shape from a tensor, can use `tensor.shape`
3. To get device şnformation from tensor, can use `tensor.device`

In [32]:
some_tensor = torch.rand(3,4)

some_tensor

tensor([[0.8662, 0.5241, 0.1902, 0.6675],
        [0.8289, 0.6829, 0.4059, 0.1163],
        [0.3656, 0.8523, 0.5780, 0.1593]])

In [33]:
print(f"Datatype of tensor: {some_tensor.dtype}")
print(f"Shape of tensor: {some_tensor.shape}") # some_tensor.size() also works same but it is a function
print(f"Device of tensor: {some_tensor.device}")

Datatype of tensor: torch.float32
Shape of tensor: torch.Size([3, 4])
Device of tensor: cpu


### Manupilating Tensors (Tensor Operations)

Tensor operations include:
* Addition
* Subtraction
* Multiplication (element-wise)
* Division
* Matrix Multiplication

In [34]:
tensor = torch.tensor([1, 2, 3])

In [35]:
print(tensor + 10), # torch.add(tensor, number) would also work
print(tensor - 10) # torch.sub(tensor, number) would also work

tensor([11, 12, 13])
tensor([-9, -8, -7])


In [36]:
print(tensor * 10), # torch.mul(tensor, number) would also work
print(tensor / 10), # torch.div(tensor, number) would also work

tensor([10, 20, 30])
tensor([0.1000, 0.2000, 0.3000])


(None,)

In [37]:
print (tensor * tensor) # Matrix multiplication

tensor([1, 4, 9])


In [38]:
%%time
value = 0
for i in range(len(tensor)):
  value += tensor[i] * tensor[i]
print(value)

tensor(14)
CPU times: user 739 µs, sys: 963 µs, total: 1.7 ms
Wall time: 1.59 ms


In [39]:
%%time
torch.matmul(tensor, tensor) # Torch's matmul is faster than manual

CPU times: user 852 µs, sys: 0 ns, total: 852 µs
Wall time: 12 ms


tensor(14)

In [40]:
torch.matmul(torch.rand(3,2), torch.rand(2,3))

tensor([[0.4455, 0.6655, 0.4746],
        [0.4205, 0.2847, 0.4944],
        [0.3018, 0.2512, 0.3486]])

#### One of the most common errors in deep learning is shape errors

Particularly matrix multiplication. There are ways to handle it.
1. Get transpose

In [41]:
tensor_A = torch.rand(2,3)
tensor_B = torch.rand(2,3)

B_transpose = tensor_B.T

torch.mm(tensor_A, B_transpose)

tensor([[0.7794, 0.7588],
        [0.4296, 0.4944]])

### Tensor Aggregation

Finding:
* Min
* Max
* Mean
* Sum
* etc.

In [42]:
tensor = torch.arange(0,101,10)
tensor, tensor.dtype

(tensor([  0,  10,  20,  30,  40,  50,  60,  70,  80,  90, 100]), torch.int64)

In [43]:
# Finding Min
torch.min(tensor), tensor.min()

(tensor(0), tensor(0))

In [44]:
#Finding Max
torch.max(tensor), tensor.max()

(tensor(100), tensor(100))

In [45]:
#Finding mean

# Input of torch.mean should be a floating point or a complex dtype but as default our tensor has the type of Long.
# So we should convert it to float before getting mean

torch.mean(tensor.type(torch.float32)), tensor.type(torch.float32).mean()

(tensor(50.), tensor(50.))

In [46]:
#Finding sum

torch.sum(tensor), tensor.sum()

(tensor(550), tensor(550))

#### Finding postition of **min** and **max**

In [47]:
print(tensor.argmin()), # Position(index)
print(tensor[0]) # Value

tensor(0)
tensor(0)


In [48]:
print(tensor.argmax()), # Position(index)
print(tensor[10]) # Value

tensor(10)
tensor(100)


### Reshaping, stacking, squeezing, and unsqueezing tensors

* **Reshaping:** Reshapes an input tensor to a defined shape
* **View:** Return a view of an input tensor of certain shape but keep the same memory as the original tensor
* **Stacking:** Combine multiple tensors on top of each other `vstack` or side by side `hstack`
* **Squeeze:** Remove all `1` dimensions from a tensor
* **Unsqueeze:** Add a `1` dimension to a target tensor
* **Permute:** Return a view of the input with dimensions permuted (swapped) in certain way.

In [49]:
import torch
x = torch.arange(1.,10.)
x, x.shape

(tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.]), torch.Size([9]))

In [50]:
x_reshaped = x.reshape(1, 9)
x_reshaped, x_reshaped.shape

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [51]:
x_view = x.view(1,9)
x_view, x_view.shape

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [52]:
# Changing a view changes the original tensor since they share the same memory

x_view[:, 0] = 5
x_view, x

(tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]]),
 tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.]))

In [53]:
x_stacked = torch.stack([x, x, x, x], dim=1)
x_stacked

tensor([[5., 5., 5., 5.],
        [2., 2., 2., 2.],
        [3., 3., 3., 3.],
        [4., 4., 4., 4.],
        [5., 5., 5., 5.],
        [6., 6., 6., 6.],
        [7., 7., 7., 7.],
        [8., 8., 8., 8.],
        [9., 9., 9., 9.]])

In [54]:
# Squeezing removes the (1) dimensions
x_reshaped, x_reshaped.shape

(tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [55]:
x_squeezed = x_reshaped.squeeze()
x_squeezed, x_squeezed.shape

(tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.]), torch.Size([9]))

In [56]:
x_squeezed.unsqueeze(dim=0), x_squeezed.unsqueeze(dim=0).shape

(tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [57]:
# torch.permute - rearenges the dimensions of a target tensor in a specified order
tensor = torch.rand(size=(224, 224, 3)) # height, width, color channels (R,G,B)

# Permute the original tensor to rearrange the axis (or dim) order
tensor_permuted = tensor.permute(2, 0, 1) # Shifts axis 0->1, 1->2, 2->0
print(f"Previous shape: {tensor.shape}")
print(f"New shape: {tensor_permuted.shape}")

Previous shape: torch.Size([224, 224, 3])
New shape: torch.Size([3, 224, 224])


In [58]:
tensor[0,0,0] = 7094683

tensor[0,0,0], tensor_permuted[0,0,0] # when the original tensor changes also the permuted tensor changes

(tensor(7094683.), tensor(7094683.))

### Indexing (Selecting data from tensors)

Indexing with PyTorch is similar to indexing with NumPy

In [59]:
import torch

tensor = torch.arange(1, 10).reshape(1,3,3)

tensor, tensor.shape

(tensor([[[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]]),
 torch.Size([1, 3, 3]))

In [60]:
tensor[0]

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [61]:
tensor[0][0]

tensor([1, 2, 3])

In [62]:
tensor[0][0][0]

tensor(1)

In [63]:
# Get all values of 0th and 1st dimensions but only index 1 on 2nd dimension

tensor[:, :, 1]

tensor([[2, 5, 8]])

In [64]:
# Get all values of the 0 dimension but only the 1 index value of 1st and 2nd dimension

tensor[:, 1, 1]

tensor([5])

In [65]:
# Get index of 0 of 0th and 1st dimension and all values of 2nd dimension

tensor[0,0,:]

tensor([1, 2, 3])

### PyTorch vs NumPy

NumPy is a popular scientific Python numerical computing library.

And because of this, PyTorch has functionality to interact with it.

* Data in NumPy -> want in PyTorch tensor -> `torch.from_numpy(ndarray)`
* PyTorch tensor -> NumPy -> `torch.Tensor.numpy()`

In [66]:
# NumPy array to tensor

import torch
import numpy as np

array = np.arange(1.0,8.0)
tensor = torch.from_numpy(array)

array, tensor

(array([1., 2., 3., 4., 5., 6., 7.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [67]:
# Default datatypes of PyTorch and NumPy are different

torch_array = torch.arange(1.0, 8.0)

array = np.arange(1.0,8.0)
tensor = torch.from_numpy(array) # When we conver from NumPy to PyTorch datatype of NumPy is also reflected!


torch_array.dtype, array.dtype, tensor.dtype

(torch.float32, dtype('float64'), torch.float64)

In [70]:
array = array + 1 # When the original np array is changed it is not reflected in converted tensor
array, tensor

(array([ 4.,  5.,  6.,  7.,  8.,  9., 10.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [71]:
tensor = torch.ones(7)
numpy_tensor = tensor.numpy()

tensor, numpy_tensor

(tensor([1., 1., 1., 1., 1., 1., 1.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

In [73]:
print(tensor.dtype) # Also converting from tensor to numpy reflects the datatype
print(numpy_tensor.dtype)

torch.float32
float32


In [76]:
tensor = tensor + 1 # Changes in tensor is not reflected in numpy converted

tensor, numpy_tensor

(tensor([4., 4., 4., 4., 4., 4., 4.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

### Reproducibility (trying to take random out of random)


In short how a neural network learns:

`start with random numbers -> tensor operations -> update random numbers to try and make them better representations of the data -> again -> again...`

To reduce the randomness in neural networks and PyTorch comes the concept of a **random seed**

Essentially what the random seed does is 'flavour' the randomness.

In [77]:
import torch

random_tensor_A = torch.rand(3,4)
random_tensor_B = torch.rand(3,4)

print(random_tensor_A)
print(random_tensor_B)
print(random_tensor_A == random_tensor_B)

tensor([[0.8160, 0.9069, 0.6600, 0.8222],
        [0.6037, 0.2086, 0.6270, 0.9353],
        [0.0462, 0.6570, 0.2725, 0.7724]])
tensor([[0.5057, 0.2820, 0.9710, 0.8961],
        [0.0539, 0.2861, 0.2926, 0.2729],
        [0.3755, 0.8786, 0.3204, 0.3459]])
tensor([[False, False, False, False],
        [False, False, False, False],
        [False, False, False, False]])


In [80]:

RANDOM_SEED = 42

torch.manual_seed(RANDOM_SEED)
random_tenseor_C = torch.rand(3, 4)

torch.manual_seed(RANDOM_SEED)
random_tenseor_D = torch.rand(3, 4)


print(random_tenseor_C)
print(random_tenseor_D)
print(random_tenseor_C == random_tenseor_D)

tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[True, True, True, True],
        [True, True, True, True],
        [True, True, True, True]])


### Running tensors and PyTorch objects on the GPUs (and making faster computations)

In [2]:
import torch

torch.cuda.is_available() # Check for GPU acces with PyTorch

True

In [3]:
device = 'cuda' if torch.cuda.is_available() else 'cpu'
device

'cuda'

In [7]:
tensor = torch.tensor([1,2,3])

print(tensor, tensor.device)

tensor([1, 2, 3]) cpu


In [8]:
tensor_on_gpu = tensor.to(device) # Moving tensor to GPU

tensor_on_gpu, tensor_on_gpu.device

(tensor([1, 2, 3], device='cuda:0'), device(type='cuda', index=0))

In [12]:
tensor_on_cpu = tensor_on_gpu.cpu().numpy() # NumPy does not work on GPU so when a NumPy action should be held, move the tensor to cpu

tensor_on_cpu

array([1, 2, 3])